### ISSUE TITLE
Error in connection to the db

### ISSUE THREAD

**Issue by GaroBozadjian** [Paul-Williamson-90/postgres_fastapi_template#1]
Th error is 
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "db" to address: Temporary failure in name resolution

**Comment by Paul-Williamson-90** [comment]
Hi @GaroBozadjian , sorry to hear this but happy to help as best I can!

Would be great if you can share the full traceback as that might give me more information to support. One thing that comes to mind currently is regarding the .env file and setting environment vars. For example I used:

```
DB_USER=user
DB_PASSWORD=password
DB_NAME=database
```

Been a while since I have ran this repo for the first time, however I believe when you launch it for the first time you will need to go into docker and access the port that PostgreSQL is running on. This will present a screen to set the credentials that will go into the .env file.

Let me know if this works / what the full traceback is and I'll see what I can figure out from it.

**Comment by Paul-Williamson-90** [comment]
Hi @GaroBozadjian ,

I haven't heard back from you so I will assume that either you have moved on or resolved your issue. Please feel free to get in touch if you need support.

Best regards,
